// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/wells/wells.proto

package go_srv_wells

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WellRequest struct {
	Aquifer              int32    `protobuf:"varint,1,opt,name=aquifer,proto3" json:"aquifer,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Depth                float64  `protobuf:"fixed64,3,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WellRequest) Reset()         { *m = WellRequest{} }
func (m *WellRequest) String() string { return proto.CompactTextString(m) }
func (*WellRequest) ProtoMessage()    {}
func (*WellRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2446187a97b3196b, []int{0}
}

func (m *WellRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WellRequest.Unmarshal(m, b)
}
func (m *WellRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WellRequest.Marshal(b, m, deterministic)
}
func (m *WellRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WellRequest.Merge(m, src)
}
func (m *WellRequest) XXX_Size() int {
	return xxx_messageInfo_WellRequest.Size(m)
}
func (m *WellRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WellRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WellRequest proto.InternalMessageInfo

func (m *WellRequest) GetAquifer() int32 {
	if m != nil {
		return m.Aquifer
	}
	return 0
}

func (m *WellRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *WellRequest) GetDepth() float64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

type Well struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Aquifer              int32    `protobuf:"varint,2,opt,name=aquifer,proto3" json:"aquifer,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Depth                float64  `protobuf:"fixed64,4,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Well) Reset()         { *m = Well{} }
func (m *Well) String() string { return proto.CompactTextString(m) }
func (*Well) ProtoMessage()    {}
func (*Well) Descriptor() ([]byte, []int) {
	return fileDescriptor_2446187a97b3196b, []int{1}
}

func (m *Well) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Well.Unmarshal(m, b)
}
func (m *Well) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Well.Marshal(b, m, deterministic)
}
func (m *Well) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Well.Merge(m, src)
}
func (m *Well) XXX_Size() int {
	return xxx_messageInfo_Well.Size(m)
}
func (m *Well) XXX_DiscardUnknown() {
	xxx_messageInfo_Well.DiscardUnknown(m)
}

var xxx_messageInfo_Well proto.InternalMessageInfo

func (m *Well) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Well) GetAquifer() int32 {
	if m != nil {
		return m.Aquifer
	}
	return 0
}

func (m *Well) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Well) GetDepth() float64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2446187a97b3196b, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type WellSearchRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Aquifer              int32    `protobuf:"varint,2,opt,name=aquifer,proto3" json:"aquifer,omitempty"`
	MinDepth             float64  `protobuf:"fixed64,3,opt,name=min_depth,json=minDepth,proto3" json:"min_depth,omitempty"`
	MaxDepth             float64  `protobuf:"fixed64,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WellSearchRequest) Reset()         { *m = WellSearchRequest{} }
func (m *WellSearchRequest) String() string { return proto.CompactTextString(m) }
func (*WellSearchRequest) ProtoMessage()    {}
func (*WellSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2446187a97b3196b, []int{3}
}

func (m *WellSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WellSearchRequest.Unmarshal(m, b)
}
func (m *WellSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WellSearchRequest.Marshal(b, m, deterministic)
}
func (m *WellSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WellSearchRequest.Merge(m, src)
}
func (m *WellSearchRequest) XXX_Size() int {
	return xxx_messageInfo_WellSearchRequest.Size(m)
}
func (m *WellSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WellSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WellSearchRequest proto.InternalMessageInfo

func (m *WellSearchRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *WellSearchRequest) GetAquifer() int32 {
	if m != nil {
		return m.Aquifer
	}
	return 0
}

func (m *WellSearchRequest) GetMinDepth() float64 {
	if m != nil {
		return m.MinDepth
	}
	return 0
}

func (m *WellSearchRequest) GetMaxDepth() float64 {
	if m != nil {
		return m.MaxDepth
	}
	return 0
}

type ListResponse struct {
	Wells                []*Well  `protobuf:"bytes,1,rep,name=wells,proto3" json:"wells,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2446187a97b3196b, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetWells() []*Well {
	if m != nil {
		return m.Wells
	}
	return nil
}

type HealthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2446187a97b3196b, []int{5}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*WellRequest)(nil), "go.srv.wells.WellRequest")
	proto.RegisterType((*Well)(nil), "go.srv.wells.Well")
	proto.RegisterType((*GetRequest)(nil), "go.srv.wells.GetRequest")
	proto.RegisterType((*WellSearchRequest)(nil), "go.srv.wells.WellSearchRequest")
	proto.RegisterType((*ListResponse)(nil), "go.srv.wells.ListResponse")
	proto.RegisterType((*HealthResponse)(nil), "go.srv.wells.HealthResponse")
}

func init() { proto.RegisterFile("proto/wells/wells.proto", fileDescriptor_2446187a97b3196b) }

var fileDescriptor_2446187a97b3196b = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xd7, 0xee, 0x76, 0x49, 0x66, 0xab, 0x48, 0x58, 0x2b, 0x11, 0xca, 0x4a, 0x44, 0x3e,
	0x45, 0x1c, 0x12, 0xb1, 0x5c, 0x10, 0xc7, 0x05, 0xb1, 0x08, 0x71, 0x21, 0x3d, 0x70, 0x41, 0x5a,
	0x99, 0xcd, 0xd0, 0x5a, 0x4d, 0xed, 0x34, 0x71, 0xff, 0x5c, 0xb8, 0xf0, 0x0a, 0xbc, 0x0a, 0x6f,
	0xc2, 0x2b, 0xf0, 0x20, 0x28, 0x76, 0x5a, 0x12, 0xd1, 0xb2, 0x97, 0x48, 0x33, 0x63, 0xff, 0x66,
	0xbe, 0x6f, 0x1c, 0x78, 0x54, 0x56, 0xda, 0xe8, 0x74, 0x83, 0x45, 0x51, 0xbb, 0x6f, 0x62, 0x33,
	0x6c, 0x34, 0xd5, 0x49, 0x5d, 0xad, 0x13, 0x9b, 0x1b, 0x5f, 0x4e, 0xb5, 0x9e, 0x16, 0x98, 0x8a,
	0x52, 0xa6, 0x42, 0x29, 0x6d, 0x84, 0x91, 0x5a, 0xb5, 0x67, 0xf9, 0x04, 0xce, 0x3f, 0x61, 0x51,
	0x64, 0xb8, 0x5c, 0x61, 0x6d, 0x58, 0x08, 0x0f, 0xc4, 0x72, 0x25, 0xbf, 0x62, 0x15, 0x92, 0x88,
	0xc4, 0xc3, 0x6c, 0x17, 0xb2, 0x0b, 0x18, 0xea, 0x8d, 0xc2, 0x2a, 0xa4, 0x11, 0x89, 0xfd, 0xcc,
	0x05, 0x4d, 0x36, 0xc7, 0xd2, 0xcc, 0xc2, 0x41, 0x44, 0x62, 0x92, 0xb9, 0x80, 0x7f, 0x86, 0xd3,
	0x06, 0xca, 0x02, 0xa0, 0x32, 0x6f, 0x41, 0x54, 0xe6, 0x5d, 0x3a, 0x3d, 0x42, 0x1f, 0x1c, 0xa4,
	0x9f, 0x76, 0xe9, 0x23, 0x80, 0x1b, 0x34, 0xed, 0xc4, 0xfc, 0x1b, 0x3c, 0x6c, 0x7a, 0x4d, 0x50,
	0x54, 0x77, 0xb3, 0x9d, 0x8c, 0x3d, 0x8e, 0x74, 0x71, 0xc7, 0xdb, 0x3f, 0x01, 0x7f, 0x21, 0xd5,
	0x6d, 0x57, 0x8a, 0xb7, 0x90, 0xea, 0x4d, 0x13, 0xdb, 0xa2, 0xd8, 0xde, 0x76, 0x27, 0xf1, 0x16,
	0x62, 0x6b, 0x8b, 0xfc, 0x25, 0x8c, 0x3e, 0xc8, 0xda, 0x64, 0x58, 0x97, 0x5a, 0xd5, 0xc8, 0x62,
	0x18, 0x5a, 0xdb, 0x43, 0x12, 0x0d, 0xe2, 0xf3, 0x2b, 0x96, 0x74, 0x77, 0x91, 0x58, 0xab, 0xdd,
	0x01, 0x1e, 0x41, 0xf0, 0x0e, 0x45, 0x61, 0x66, 0xfb, 0xbb, 0x01, 0x50, 0x3d, 0xb7, 0x23, 0x7b,
	0x19, 0xd5, 0xf3, 0xab, 0x9f, 0xd4, 0x2d, 0x67, 0x82, 0xd5, 0x5a, 0xde, 0x21, 0xbb, 0x86, 0x33,
	0x77, 0x83, 0x85, 0x7d, 0xec, 0x5f, 0x3b, 0xc6, 0x97, 0xfd, 0x4a, 0xbf, 0x03, 0x3f, 0x61, 0xd7,
	0xe0, 0xdd, 0xa0, 0x69, 0xa8, 0xf5, 0x7f, 0x28, 0xe3, 0x7e, 0xa5, 0xab, 0x90, 0x9f, 0xb0, 0xf7,
	0xe0, 0xbf, 0x95, 0x2a, 0x77, 0x90, 0xa7, 0xff, 0x2a, 0xec, 0xed, 0xe2, 0x1e, 0xd6, 0x47, 0x80,
	0xd7, 0x15, 0x0a, 0x83, 0xf6, 0xc1, 0x3c, 0x3e, 0x60, 0x57, 0x8b, 0x39, 0xe0, 0x24, 0xbf, 0xf8,
	0xfe, 0xeb, 0xf7, 0x0f, 0x1a, 0x70, 0x3f, 0x5d, 0x3f, 0x77, 0x7f, 0xc0, 0x2b, 0xf2, 0xec, 0xcb,
	0x99, 0x7d, 0xd9, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x89, 0x3b, 0xd5, 0x95, 0x20, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WellServiceClient is the client API for WellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WellServiceClient interface {
	Health(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetWells(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ListResponse, error)
	FindWells(ctx context.Context, in *WellSearchRequest, opts ...grpc.CallOption) (*ListResponse, error)
	CreateWell(ctx context.Context, in *WellRequest, opts ...grpc.CallOption) (*Well, error)
}

type wellServiceClient struct {
	cc *grpc.ClientConn
}

func NewWellServiceClient(cc *grpc.ClientConn) WellServiceClient {
	return &wellServiceClient{cc}
}

func (c *wellServiceClient) Health(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/go.srv.wells.WellService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wellServiceClient) GetWells(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/go.srv.wells.WellService/GetWells", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wellServiceClient) FindWells(ctx context.Context, in *WellSearchRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/go.srv.wells.WellService/FindWells", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wellServiceClient) CreateWell(ctx context.Context, in *WellRequest, opts ...grpc.CallOption) (*Well, error) {
	out := new(Well)
	err := c.cc.Invoke(ctx, "/go.srv.wells.WellService/CreateWell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WellServiceServer is the server API for WellService service.
type WellServiceServer interface {
	Health(context.Context, *GetRequest) (*HealthResponse, error)
	GetWells(context.Context, *GetRequest) (*ListResponse, error)
	FindWells(context.Context, *WellSearchRequest) (*ListResponse, error)
	CreateWell(context.Context, *WellRequest) (*Well, error)
}

func RegisterWellServiceServer(s *grpc.Server, srv WellServiceServer) {
	s.RegisterService(&_WellService_serviceDesc, srv)
}

func _WellService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WellServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.srv.wells.WellService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WellServiceServer).Health(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WellService_GetWells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WellServiceServer).GetWells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.srv.wells.WellService/GetWells",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WellServiceServer).GetWells(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WellService_FindWells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WellSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WellServiceServer).FindWells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.srv.wells.WellService/FindWells",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WellServiceServer).FindWells(ctx, req.(*WellSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WellService_CreateWell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WellServiceServer).CreateWell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.srv.wells.WellService/CreateWell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WellServiceServer).CreateWell(ctx, req.(*WellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WellService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.srv.wells.WellService",
	HandlerType: (*WellServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _WellService_Health_Handler,
		},
		{
			MethodName: "GetWells",
			Handler:    _WellService_GetWells_Handler,
		},
		{
			MethodName: "FindWells",
			Handler:    _WellService_FindWells_Handler,
		},
		{
			MethodName: "CreateWell",
			Handler:    _WellService_CreateWell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wells/wells.proto",
}
